services:
  gateway:
    build: .
    restart: unless-stopped
    command: [ 'tcp://mqtt-broker:1883', 'coap-mqtt-gateway', '5688' ]
    ports:
      - "5688:5688"
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: [ 'sleep', 'infinity' ]
    depends_on:
      - gateway
      - mqtt-broker